# Misc
alias cd..='cd ..'
alias ws='cd ~/workspace'
alias ln='ln -i'
alias uls='cd /usr/local/share'

# Clojure
alias clj='lein repl'

# Emacs
alias vi="emacsclient -t"
alias e="emacsclient -t"
alias em="nohup emacsclient -c -a emacs"

# Android SDK
alias adbkill='sudo /usr/local/share/android-sdk/platform-tools/adb kill-server'
alias adbstart='sudo /usr/local/share/android-sdk/platform-tools/adb start-server'
alias adbrestart='adbkill;adbstart'

# Git
alias g='git'

# from http://stackoverflow.com/questions/7066325/how-to-list-show-git-aliases
alias gitalias="git config --get-regexp ^alias\."
