#!/usr/bin/env bash

set -euo pipefail

source_dir=$(pwd)/secrets
dest_bucket=secrets-f3ba7cb4

backblaze-b2 sync \
             --threads 3 \
             --replaceNewer \
             --excludeRegex "(.*\/\..*)|(.*\/tmp)|(.*\.Trash.*)|(.*\/wip)|(.*\/WIP)" \
             --excludeAllSymlinks \
             --keepDays 365 \
             "$source_dir" "b2://$dest_bucket"
