#!/usr/bin/env bash

set -euo pipefail

source_dir=$(pwd)/secrets
dest_bucket=secrets-f3ba7cb4

for f in $(find "$source_dir" -type f); do
    filename=$(basename "$f")
    backblaze-b2 upload-file \
                 --threads 3 \
                 --noProgress \
                 "$dest_bucket" \
                 "$f" \
                 "$filename"
done

datetime=$(date --iso-8601=second)
message="Update secrets ($datetime)"
git add "$source_dir"
git commit -m "$message"
git push
