#!/usr/bin/env bash

set -euo pipefail

temp_dir=$(mktemp -d -t "ar-init-tarsnap.XXXXXXXXXX")

LIGHT_GREEN='\033[1;92m'
NC='\033[0m' # No Color

secret_bin=$(pwd)/home/.local/bin/secret
secrets_dir=$(pwd)/secrets
system_dir=/var/lib/tarsnap

echo -e "${LIGHT_GREEN}Install Tarsnap...${NC}"
sudo pamac install tarsnap

echo -e "${LIGHT_GREEN}Creating dirs...${NC}"
sudo mkdir -p $system_dir/cache
sudo mkdir -p /etc/tarsnap

echo -e "${LIGHT_GREEN}Copying keys in /root...${NC}"
for f in $(find "$secrets_dir" -type f -and -name 'tarsnap*.enc'); do
    encrypted_f=$(readlink -f "$f")
    filename=$(basename "$f")
    temp_f=$temp_dir/${filename%.enc}
    root_f=/root/${filename%.enc}

    $secret_bin -r -s "$encrypted_f" -d "$temp_f"
    sudo mv -iv "$temp_f" "$root_f"
    sudo chmod 600 "$root_f"
done

echo -e "${LIGHT_GREEN}Copying configuration file...${NC}"
$secret_bin -r -s etc/tarsnap/tarsnap.conf.enc -d etc/tarsnap/tarsnap.conf
sudo mv -iv tarsnap.conf /etc/tarsnap
shred -u -n 19 tarsnap.conf
