#!/usr/bin/env bash

set -euo pipefail

# For skipping sections, use this trick:
#
#   cat >/dev/null <<LABEL
#
# see the brilliant answer here: https://stackoverflow.com/a/45538151

LIGHT_YELLOW='\033[1;93m'
LIGHT_GREEN='\033[1;92m'
LIGHT_RED='\033[1;91m'
NC='\033[0m' # No Color

secret_bin=$(pwd)/home/.local/bin/secret
temp_dir=$(mktemp -d -t "ar-init-home.XXXXXXXXXX")

echo -e "${LIGHT_GREEN}Installing dependencies...${NC}"
sudo pamac install meld

echo -e "${LIGHT_GREEN}Creating directories...${NC}"
mkdir -p $HOME/.local/bin
mkdir -p $HOME/tmp

pushd home > /dev/null

echo -e "${LIGHT_GREEN}Diffing unencrypted home files...${NC}"
for f in $(find . -type f -and -not -name '*.enc'); do
    local_f=$(readlink --no-newline --canonicalize-missing "$HOME/$f")
    set +e
    (set -x; diff --new-file "$local_f" "$f" > /dev/null)
    exit_code=$?
    set -e

    local_d=$(dirname "$local_f")
    echo -e "${LIGHT_GREEN}Creating $local_d directory...${NC}"
    mkdir -p "$local_d"

    case $exit_code in
        0) echo -e "${LIGHT_GREEN}File $local_f already up-to-date${NC}.";;
        1) echo -e "${LIGHT_YELLOW}File $local_f is outdated or missing, opening diff tool...${NC}"; set +e; meld "$local_f" "$f"; set -e;;
        *) echo -e "${LIGHT_RED}Unidentified $f diff exit code ($exit_code), skipping.${NC}";;
    esac
done

echo -e "${LIGHT_GREEN}Making $HOME/.local/bin files executable...${NC}"
find "$HOME/.local/bin" -type f -and -not -executable -exec chmod u+x {} ';'

echo -e "${LIGHT_GREEN}Diffing encrypted dot files...${NC}"
for f in $(find . -type f -and -name '*.enc'); do
    encrypted_f=$(readlink -f --no-newline --canonicalize-missing "$f")
    temp_f=$(readlink -f --no-newline --canonicalize-missing "$temp_dir/${f%.enc}")

    set +e
    $secret_bin -r -s "$encrypted_f" -d "$temp_f"
    if [ $? -eq 0 ]; then
        meld "$HOME/$f" "$temp_f"
    fi
    shred -u -n 19 "$temp_f"
    set -e
done

popd
