#!/usr/bin/env bash

set -euo pipefail

# For skipping sections, use this trick:
#
#   cat >/dev/null <<HUB
#
# see the brilliant answer here: https://stackoverflow.com/a/45538151

LIGHT_YELLOW='\033[1;93m'
LIGHT_GREEN='\033[1;92m'
LIGHT_RED='\033[1;91m'
NC='\033[0m' # No Color

temp_dir=$(mktemp -d -t "ar-settings.XXXXXXXXXX")

echo -e "${LIGHT_GREEN}Creating directories...${NC}"
mkdir -p $HOME/bin
mkdir -p $HOME/tmp

echo -e "${LIGHT_GREEN}Copying bin scripts...${NC}"
for f in $(find ./bin/ -type f -and -not -name '*.enc'); do
    set +e
    (set -x; diff --new-file "$HOME/$f" "$f" > /dev/null)
    exit_code=$?
    set -e

    case $exit_code in
        0) echo -e "${LIGHT_GREEN}File $HOME/$f already up-to-date${NC}.";;
        1) echo -e "${LIGHT_YELLOW}File $HOME/$f is outdated, comparing...${NC}"; set +e; meld "$HOME/$f" "$f"; set -e;;
        *) echo -e "${LIGHT_RED}Unidentified $f diff failure, skipping.${NC}";;
    esac
done

echo -e "${LIGHT_GREEN}Diffing plain text dot files...${NC}"

pushd home > /dev/null

for f in $(find . -type f -and -not -name '*.enc'); do
    set +e
    meld "$HOME/$f" "$f"
    set -e
done

echo -e "${LIGHT_GREEN}Diffing encrypted dot files...${NC}"

for f in $(find . -type f -and -name '*.enc'); do
    encrypted_f=$(readlink -f "$f")
    unencrypted_f="$temp_dir/home/${f%.enc}"
    set +e
    ../bin/secret -r -s "$encrypted_f" -d "$unencrypted_f"
    if [ $? -eq 0 ]; then
        meld "$HOME/$f" $unencrypted_f
    fi
    shred -u -n 19 $unencrypted_f
    set -e
done

popd
