#!/usr/bin/env bash

set -euo pipefail

# For skipping sections, use this trick:
#
#   cat >/dev/null <<HUB
#
# see the brilliant answer here: https://stackoverflow.com/a/45538151

LIGHT_GREEN='\033[1;32m'
NC='\033[0m' # No Color

echo -e "${LIGHT_GREEN}Installing packages...${NC}"
sudo pamac install \
     rxvt-unicode bash-completion \
     qastools scrot cmake arandr the_silver_searcher \
     xsel docker docker-compose tree byzanz perl-image-exiftool \
     rlwrap xclip xorg-xbacklight texinfo meld python-pip cryptsetup \
     colordiff texlive-latexextra kubectl hub keybase kbfs \
     keybase-gui tk jq discount

# not found from apt: global texlive-base-extra console-data
