#!/usr/bin/env bash

set -euo pipefail

# For skipping sections, use this trick:
#
#   cat >/dev/null <<HUB
#
# see the brilliant answer here: https://stackoverflow.com/a/45538151

LIGHT_GREEN='\033[1;32m'
NC='\033[0m' # No Color

declare -a packages
packages=(gp-saml-gui-git vpn-slice \
          yarn-completion-git leiningen-completions \
          adr-tools pandoc-bin zeal backblaze-b2 gtk-recordmydesktop \
          nordvpn-bin \
          emacs-git cask)

for pkg in "${packages[@]}"; do
    echo -n "Install $pkg from AUR (y/n)? "
    stty raw -echo ; answer=$(head -c 1) ; stty sane

    if echo "$answer" | grep -iq "^y" ;then
        echo -e "\n${LIGHT_GREEN}Installing $pkg...${NC}"
        pamac build "$pkg"
    else
        echo -e "Skipping."
    fi
done
