#!/usr/bin/env bash

set -euo pipefail

# For skipping sections, use this trick:
#
#   cat >/dev/null <<HUB
#
# see the brilliant answer here: https://stackoverflow.com/a/45538151

LIGHT_GREEN='\033[1;32m'
NC='\033[0m' # No Color

echo -e "${LIGHT_GREEN}Installing packages...${NC}"
(set -x; sudo pamac install \
     rxvt-unicode ttf-jetbrains-mono bash-completion \
     pavucontrol rofi keepassxc \
     qastools scrot cmake arandr the_silver_searcher \
     yarn nvm leiningen meld \
     docker docker-compose tree dsnutils byzanz perl-image-exiftool \
     rlwrap xsel xclip xorg-xfontsel xorg-xev xorg-xbacklight texinfo python-pip cryptsetup \
     colordiff texlive-latexextra kubectl hub keybase kbfs \
     keybase-gui tk jq discount)

# not found from apt: global texlive-base-extra console-data
