#!/usr/bin/env bash

set -euo pipefail

url=https://s3.us-west-000.backblazeb2.com
bucket_name=clones-wpn8au1e
mount_point=/home/partimag

set +x
s3fs "$bucket_name" -o url="$url" -o parallel_count=30 -o multireq_max=30 "$mount_point"
set -x
